DROP TABLE province CASCADE;
DROP TABLE district CASCADE;
DROP TABLE town CASCADE;
DROP TABLE shopinfo CASCADE;
DROP TABLE proorder CASCADE;
DROP TABLE cusinfo CASCADE;
DROP TABLE proorderinfo CASCADE;